site_name: 'Dataset Explorer'
site_url: 'https://remirigal.github.io/DatasetExplorer'
repo_url: 'https://github.com/RemiRigal/DatasetExplorer'
repo_name: 'RemiRigal/DatasetExplorer'

nav:
  - Home: 'index.md'
  - Getting Started:
      - Using Docker: 'getting-started/docker.md'
      - From Source: 'getting-started/from-source.md'
  - Writing Custom Tools:
      - Custom Tools: 'custom-tools/index.md'
      - Guidelines: 'custom-tools/guidelines.md'
      - Using Parameters: 'custom-tools/parameters.md'
      - Tools API: 'custom-tools/api.md'

theme:
  name: material
  palette:
    primary: blue
    accent: deep orange

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_object_full_path: false
            show_root_heading: false
            show_root_toc_entry: false
      watch:
        - backend/

extra_css:
  - assets/stylesheets/docs.css
