name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ${{ github.workspace }}/docs/requirements.txt
          python -m pip install -r ${{ github.workspace }}/backend/requirements.txt
          sudo apt-get install libsndfile1-dev

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote rm origin
          git remote add origin "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Deploy docs
        run: |
          PYTHONPATH=${{ github.workspace }}/backend mkdocs gh-deploy --config-file "${{ github.workspace }}/mkdocs.yml" --force
