name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Deploy docs
        uses: RemiRigal/mkdocs-deploy-gh-pages@patch-1
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
          PYTHONPATH: backend/
